export interface Product {
  id: string;
  name: string;
  type?: string;
  categoryType?: string;
  category?: string; // e.g. monster, exotic, normal, tanks, filters, pellet, etc.
  price: number;
  stock?: number;
  quantity?: number;
  description?: string;
  image?: string;
  imageBase64?: string;
  gallery?: string[];
  // Fish specs
  scientificName?: string;
  careLevel?: "Easy" | "Moderate" | "Expert";
  tankSize?: string;
  feedingInfo?: string;
  // Other specs
  brand?: string;
  weight?: string;
}

export const mockProducts: Product[] = [
  // ==================== FISHES: MONSTER ====================
  {
    id: "arowana",
    name: "Golden Arowana",
    type: "fish",
    category: "monster",
    price: 1800,
    stock: 3,
    description: "The legendary Dragon Fish. Carries striking metallic golden scales that represent wealth and power. Highly interactive and majestic swimmer.",
    image: "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=80",
    ],
    scientificName: "Scleropages formosus",
    careLevel: "Expert",
    tankSize: "250 Gallons",
    feedingInfo: "Carnivorous: feeds on live/frozen shrimp, small fish, and floating monster pellets.",
  },
  {
    id: "alligator-gar",
    name: "Platinum Alligator Gar",
    type: "fish",
    category: "monster",
    price: 950,
    stock: 2,
    description: "Striking pure white platinum coloration. A rare prehistoric monster fish featuring dual rows of large teeth and diamond-shaped scales.",
    image: "https://images.unsplash.com/photo-1508962914676-134849a727f0?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1508962914676-134849a727f0?w=600&auto=format&fit=crop&q=80",
    ],
    scientificName: "Atractosteus spatula",
    careLevel: "Expert",
    tankSize: "400 Gallons",
    feedingInfo: "Feeds on fish fillets, whole shrimp, and sinking carnivore pellets.",
  },
  {
    id: "stingray",
    name: "Black Diamond Stingray",
    type: "fish",
    category: "monster",
    price: 1450,
    stock: 4,
    description: "Stunning velvet black body decorated with brilliant white spots. One of the most sought-after freshwater stingrays in the aquascaping world.",
    image: "https://images.unsplash.com/photo-1560275669-46c5a88d6a4c?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1560275669-46c5a88d6a4c?w=600&auto=format&fit=crop&q=80",
    ],
    scientificName: "Potamotrygon leopoldi",
    careLevel: "Expert",
    tankSize: "300 Gallons",
    feedingInfo: "Benthic feeder: requires sinking earthworms, chopped shrimp, and premium sinking tablets.",
  },
  {
    id: "giant-gourami",
    name: "Red Tail Giant Gourami",
    type: "fish",
    category: "monster",
    price: 320,
    stock: 5,
    description: "Highly intelligent and interactive pet fish. Develops bright red borders on its fins and tail as it matures.",
    image: "https://images.unsplash.com/photo-1534043464124-3be32fe000c9?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1534043464124-3be32fe000c9?w=600&auto=format&fit=crop&q=80",
    ],
    scientificName: "Osphronemus laticlavius",
    careLevel: "Moderate",
    tankSize: "200 Gallons",
    feedingInfo: "Omnivorous: loves fresh vegetables (romaine lettuce, peas) and large floating pellets.",
  },
  {
    id: "redtail-catfish",
    name: "Redtail Catfish",
    type: "fish",
    category: "monster",
    price: 150,
    stock: 8,
    description: "A fast-growing freshwater giant. Distinctive dark back, white underbelly, and a beautifully colored orange-red caudal fin.",
    image: "https://images.unsplash.com/photo-1524704654690-b56c05c78a02?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1524704654690-b56c05c78a02?w=600&auto=format&fit=crop&q=80",
    ],
    scientificName: "Phractocephalus hemioliopterus",
    careLevel: "Expert",
    tankSize: "500 Gallons",
    feedingInfo: "Gluttonous carnivore: feeds on raw fish fillets, crabs, and sinking catfish pellets.",
  },

  // ==================== FISHES: EXOTIC ====================
  {
    id: "betta",
    name: "Crown Betta Splendens",
    type: "fish",
    category: "exotic",
    price: 65,
    stock: 15,
    description: "Exquisite comb-like tail extensions. Hand-selected for deep iridescent coloration and active flare behaviour.",
    image: "https://images.unsplash.com/photo-1524704796725-9fc3044a58b2?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1524704796725-9fc3044a58b2?w=600&auto=format&fit=crop&q=80",
    ],
    scientificName: "Betta splendens",
    careLevel: "Easy",
    tankSize: "5 Gallons",
    feedingInfo: "Granivorous: eats premium Betta micro-pellets, freeze-dried bloodworms, and live daphnia.",
  },
  {
    id: "flowerhorn",
    name: "Super Red Dragon Flowerhorn",
    type: "fish",
    category: "exotic",
    price: 450,
    stock: 6,
    description: "Features a massive head hump (Kok) and a fiery red pearled body. Possesses a highly responsive personality and follows fingers.",
    image: "https://images.unsplash.com/photo-1571752726101-9f77cf66427d?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1571752726101-9f77cf66427d?w=600&auto=format&fit=crop&q=80",
    ],
    scientificName: "Cichlasoma sp.",
    careLevel: "Moderate",
    tankSize: "75 Gallons",
    feedingInfo: "Highly active: thrives on Flowerhorn-specific hump-development pellets and frozen krill.",
  },
  {
    id: "discus",
    name: "Red Cover Discus",
    type: "fish",
    category: "exotic",
    price: 180,
    stock: 12,
    description: "Elegant, disc-shaped king of the Amazon. Possesses a solid, vibrant red-orange hue with zero strain bars.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=80",
    ],
    scientificName: "Symphysodon aequifasciatus",
    careLevel: "Expert",
    tankSize: "55 Gallons",
    feedingInfo: "Sensitive: requires beef heart mixes, premium flake foods, and regular frozen bloodworms.",
  },
  {
    id: "oscar",
    name: "Fiery Tiger Oscar",
    type: "fish",
    category: "exotic",
    price: 85,
    stock: 10,
    description: "A gorgeous contrast of deep black scales overlaid with fiery orange patterns. Extremely intelligent and displays active curiosity.",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&auto=format&fit=crop&q=80",
    ],
    scientificName: "Astronotus ocellatus",
    careLevel: "Moderate",
    tankSize: "75 Gallons",
    feedingInfo: "Eats cichlid large pellets, freeze-dried mealworms, and krill.",
  },
  {
    id: "frontosa",
    name: "Cyphotilapia Frontosa",
    type: "fish",
    category: "exotic",
    price: 140,
    stock: 8,
    description: "Stately cichlid from Lake Tanganyika. Features distinct blue and white vertical banding and a large frontal lobe hump in males.",
    image: "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=600&auto=format&fit=crop&q=80",
    ],
    scientificName: "Cyphotilapia frontosa",
    careLevel: "Moderate",
    tankSize: "125 Gallons",
    feedingInfo: "Requires high-protein cichlid sinking pellets and frozen mysis shrimp.",
  },

  // ==================== FISHES: NORMAL ====================
  {
    id: "goldfish",
    name: "Red & White Oranda Goldfish",
    type: "fish",
    category: "normal",
    price: 45,
    stock: 20,
    description: "Adorable fancy goldfish with a large, raspberry-like red hood (Wen) and a flowing lacy tail.",
    image: "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=600&auto=format&fit=crop&q=80",
    ],
    scientificName: "Carassius auratus",
    careLevel: "Easy",
    tankSize: "30 Gallons",
    feedingInfo: "Consumes sinking goldfish pellets, cooked peas (deshelled), and high-fiber flakes.",
  },
  {
    id: "molly",
    name: "Black Lyretail Molly",
    type: "fish",
    category: "normal",
    price: 8,
    stock: 50,
    description: "Vibrant solid black cichlid-like livebearer with an elegant lyre-shaped tail fin. Great algae grazer.",
    image: "https://images.unsplash.com/photo-1609142588383-8a3070b4317f?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1609142588383-8a3070b4317f?w=600&auto=format&fit=crop&q=80",
    ],
    scientificName: "Poecilia sphenops",
    careLevel: "Easy",
    tankSize: "15 Gallons",
    feedingInfo: "Eats tropical flakes, spirulina pellets, and small live brine shrimp.",
  },
  {
    id: "guppy",
    name: "Neon Blue Moscow Guppy",
    type: "fish",
    category: "normal",
    price: 12,
    stock: 40,
    description: "Dazzling metallic neon-blue body with a massive, veil-like fan tail. Lively and perfect for community tanks.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=80",
    ],
    scientificName: "Poecilia reticulata",
    careLevel: "Easy",
    tankSize: "10 Gallons",
    feedingInfo: "Tropical micro-pellets, crushed flakes, and live baby brine shrimp.",
  },
  {
    id: "platy",
    name: "Sunburst Mickey Mouse Platy",
    type: "fish",
    category: "normal",
    price: 6,
    stock: 35,
    description: "Cheerful bright orange body featuring a classic 'Mickey Mouse' head pattern at the base of the tail.",
    image: "https://images.unsplash.com/photo-1609142588383-8a3070b4317f?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1609142588383-8a3070b4317f?w=600&auto=format&fit=crop&q=80",
    ],
    scientificName: "Xiphophorus maculatus",
    careLevel: "Easy",
    tankSize: "15 Gallons",
    feedingInfo: "Omnivorous flake foods, blanched vegetables, and crushed premium pellets.",
  },
  {
    id: "swordtail",
    name: "Red Neon Swordtail",
    type: "fish",
    category: "normal",
    price: 7,
    stock: 30,
    description: "Lively red livebearer, males boast a long, sword-like tail extension. A highly active community fish.",
    image: "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=600&auto=format&fit=crop&q=80",
    ],
    scientificName: "Xiphophorus helleri",
    careLevel: "Easy",
    tankSize: "20 Gallons",
    feedingInfo: "Eats small pellets, high-grade flakes, and frozen bloodworms.",
  },

  // ==================== EQUIPMENTS ====================
  {
    id: "tank-rimless-100",
    name: "Ultra-Clear Rimless Glass Tank",
    type: "equipment",
    category: "tanks",
    price: 650,
    stock: 5,
    description: "Premium rimless glass tank with 45-degree mitered edges and low-iron ultra-clear glass, offering high light transmittance.",
    image: "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?w=600&auto=format&fit=crop&q=80"],
    brand: "K.T Aquascapes",
  },
  {
    id: "filter-canister-300",
    name: "OASE BioMaster Thermo 350",
    type: "equipment",
    category: "filters",
    price: 289,
    stock: 8,
    description: "High-end canister filter with integrated heater, pre-filter module for easy maintenance, and multi-stage biological filtration.",
    image: "https://images.unsplash.com/photo-1508962914676-134849a727f0?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1508962914676-134849a727f0?w=600&auto=format&fit=crop&q=80"],
    brand: "OASE",
  },
  {
    id: "air-pump-silent",
    name: "Eheim Air Pump 200",
    type: "equipment",
    category: "pumps",
    price: 45,
    stock: 12,
    description: "Extremely quiet dual-outlet air pump with adjustable air flow. Includes air diffusers and premium airline tubing.",
    image: "https://images.unsplash.com/photo-1524704654690-b56c05c78a02?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1524704654690-b56c05c78a02?w=600&auto=format&fit=crop&q=80"],
    brand: "Eheim",
  },
  {
    id: "light-led-wrgb",
    name: "Chihiros WRGB II PRO Slim",
    type: "equipment",
    category: "lights",
    price: 195,
    stock: 6,
    description: "Smart Bluetooth-controllable WRGB LED light. Ideal for high-demand planted tanks, boosting brilliant fish coloration.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=80"],
    brand: "Chihiros",
  },
  {
    id: "heater-titanium",
    name: "Schego Titanium Heater 300W",
    type: "equipment",
    category: "heaters",
    price: 75,
    stock: 10,
    description: "Shatterproof titanium heating element. Excellent heat transfer, highly durable and ideal for marine or freshwater setups.",
    image: "https://images.unsplash.com/photo-1571752726101-9f77cf66427d?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1571752726101-9f77cf66427d?w=600&auto=format&fit=crop&q=80"],
    brand: "Schego",
  },
  {
    id: "accessories-scape-tool",
    name: "Stainless Steel Aquascaping Tool Kit",
    type: "equipment",
    category: "accessories",
    price: 38,
    stock: 25,
    description: "Five-piece medical-grade stainless steel kit. Includes straight scissors, curved scissors, substrate spatula, and dual tweezers.",
    image: "https://images.unsplash.com/photo-1534043464124-3be32fe000c9?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1534043464124-3be32fe000c9?w=600&auto=format&fit=crop&q=80"],
    brand: "K.T Aquascapes",
  },

  // ==================== FISH FOOD ====================
  {
    id: "food-pellet-hikari",
    name: "Hikari Cichlid Gold Pellets",
    type: "food",
    category: "pellet",
    price: 18,
    stock: 30,
    description: "Color-enhancing daily diet for cichlids and larger tropical fish. Rich in astaxanthin and vitamin C.",
    image: "https://images.unsplash.com/photo-1609142588383-8a3070b4317f?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1609142588383-8a3070b4317f?w=600&auto=format&fit=crop&q=80"],
    weight: "250g",
  },
  {
    id: "food-flake-tetra",
    name: "TetraMin Tropical Flakes",
    type: "food",
    category: "flake",
    price: 12,
    stock: 40,
    description: "Classic tropical flake food formulated with prebiotic immunity support. Cleans water formula avoids clouding.",
    image: "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=600&auto=format&fit=crop&q=80"],
    weight: "200g",
  },
  {
    id: "food-frozen-bloodworm",
    name: "Hikari Bio-Pure Frozen Bloodworms",
    type: "food",
    category: "frozen",
    price: 15,
    stock: 18,
    description: "Three-step sterilized frozen bloodworms. Enriched with multi-vitamins to encourage spawning and vibrant energy.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=80"],
    weight: "100g (32 Cubes)",
  },
  {
    id: "food-live-daphnia",
    name: "Live Cultured Daphnia Magna",
    type: "food",
    category: "live",
    price: 14,
    stock: 10,
    description: "Active live food culture. Provides excellent gut nutrition and triggers hunting instinct in exotic species.",
    image: "https://images.unsplash.com/photo-1524704796725-9fc3044a58b2?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1524704796725-9fc3044a58b2?w=600&auto=format&fit=crop&q=80"],
    weight: "1 Bag (Live Culture)",
  },
  {
    id: "food-premium-northfin",
    name: "NorthFin Krill Gold Formula",
    type: "food",
    category: "premium",
    price: 24,
    stock: 22,
    description: "100% Antarctic Krill, filler-free formula. Perfect for all tropical fish seeking natural, pigment-rich proteins.",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&auto=format&fit=crop&q=80"],
    weight: "150g",
  }
];

export const getProducts = () => mockProducts;

export const getProductById = (id: string) => 
  mockProducts.find(product => product.id === id) || null;

export const getProductsByCategory = (type: "fish" | "equipment" | "food", category: string) => 
  mockProducts.filter(product => product.type === type && product.category === category);
